version: '3'

services:
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - mynet
  authDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
    - authdbdata:/var/lib/mysql
    networks:
      - mynet
  authDBMigration:
    image: authdbmigration
    environment:
      - DATABASE_URL=authdb
    networks:
      - mynet
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authdb
    ports:
    - "5000:5000"
    networks:
      - mynet
  marketDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - mynet
    volumes:
      - marketdbdata:/var/lib/mysql
  marketDBMigration:
    image: marketdbmigration
    environment:
      - DATABASE_URL=marketdb
    networks:
      - mynet
  admin:
    image: admin
    environment:
      - DATABASE_URL=marketdb
    ports:
    - "5001:5001"
    networks:
      - mynet
  customer:
    image: customer
    environment:
      - DATABASE_URL=marketdb
    ports:
    - "5002:5002"
    deploy:
      replicas: 3
    networks:
      - mynet
  redis:
    image: redis
    networks:
      - mynet
  employee:
    image: employee
    environment:
      - DATABASE_URL=marketdb
      - REDIS_HOST=redis
    ports:
    - "5003:5003"
    deploy:
      replicas: 3
    networks:
      - mynet
  daemon:
    image: daemon
    environment:
      - DATABASE_URL=marketdb
      - REDIS_HOST=redis
    networks:
      - mynet

volumes:
  authdbdata:
  marketdbdata:

networks:
  mynet:
    driver: overlay